---
title: "Visualization"
author: "Vivian Bui"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggforce) 
```


```{r}
# Get subset of LWBS 
LWBS <- df_p %>% filter(Time_A == "LWBS")

# Remove TBD (patients who have not yet receive a bed)
df_p <- df_p %>% filter(Time_A != "TBD")

```


```{r}
# Plot 
df_er %>%
   mutate(across(Day, factor, levels=c("1","2","3", "4","5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"))) %>%
    ggplot(aes(x= Waiting, fill = Method)) +
    geom_density(alpha=.45, col=NA) +
    facet_wrap(vars(Day)) +
    scale_y_continuous(name = "Density") + 
    labs(title = 'Distribution of Waiting Patients by Day', 
            subtitle = "Overcrowding Rate: High",
            caption = "Result of 100 simulations") + 
    theme_bw() + 
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5)) 
```



```{r}
# Since the weight of Age < 1.0, to categorize patients into Priority Groups, 
  # we can just use the Acute Level 

# Wait Time by Priority Group 
ggplot(df_p, aes(y=Total_Wait_Time, x=Method)) +
    geom_violin() + 
    scale_y_continuous(name = "Wait Time") + 
    scale_x_discrete(name = "Method") +
    labs(title = 'Distribution of Wait Time across Methods', 
            subtitle = "Overcrowding Rate: High",
            caption = "Result of 100 simulations") +  
    theme_minimal() +
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5),
          plot.background=element_blank()) 
```



```{r}
# Compare the % of LWBS in each method 
df_p %>% group_by(Method) %>% 
  summarise(percent = round(sum(Time_A == "LWBS")*100/n(),2), 
            .groups = 'drop') %>% 
  ggplot(aes(x=Method, y=percent)) + 
  geom_col(width = 0.5, fill="#004c6d") + 
  scale_y_continuous(name = "Percent of LWBS (%)") + 
  scale_x_discrete(name = "Method") + 
  geom_text(size = 3, color = "black", aes(label=percent), 
            position=position_dodge(width=0.9), vjust=-0.8) +
  labs(title = 'The Percentage of LWBS over All Visited Patients across Methods', 
            subtitle = "Overcrowding Rate: High",
            caption = "Result of 100 simulations") +
  theme_minimal() + 
  theme(plot.title=element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) 
```
```{r}
# Compare the % of LWBS in each Priority Group across method 
  # Percent calculation method: within each AcuteLv, 
  # LWBS/all patients with the same AcuteLv

df_p %>% group_by(AcuteLv, Method) %>% 
  summarise(percent = round(sum(Time_A == "LWBS")*100/n(),2), .groups = 'drop') %>% 
    ggplot(aes(x=Method, y=percent, fill=Method)) + 
    geom_bar(stat="identity", position=position_dodge()) + 
    facet_wrap(vars(factor(AcuteLv)), 
               labeller = as_labeller(c(`1` = "Group 1", `2` = "Group 2", 
                      `3` = "Group 3", `4` = "Group 4", `5`="Group 5"))) +
    geom_text(size = 2, color = "black", aes(label=percent), 
              position=position_dodge(width=0.9), vjust=-0.25) + 
    scale_y_continuous(name = "Percent of LWBS (%)") + 
    scale_x_discrete(name = "Priority Group") + 
    scale_fill_brewer(palette = "RdBu") + 
    labs(title='The percentage of LWBS across Priority Groups',
            subtitle = "Overcrowding Rate: High",
            caption="Result of 100 simulations") + 
    theme_minimal() + 
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
```


```{r}
# Mean Satisfaction Score by Day across Methods
df_p %>% group_by(Day_C, Method) %>% filter(Time_A != "TBD") %>% 
  summarise(mean_SF = round(mean(SF_Score),2)) %>% 
  ggplot() +
   geom_line(aes(x=Day_C, y=mean_SF, color = Method), stat="identity") +
    scale_y_continuous(name = "Mean Satisfaction Score") + 
    scale_x_continuous(name = "Day", breaks=seq(1,15,by=1)) + 
    labs(title='End-of-day Average Satisfaction Score',
            subtitle = "Overcrowding Rate: High",
            caption="Result of 100 simulations") + 
    theme_minimal() + 
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5)) 
    
```

```{r}

# Mean Satisfaction Score by Priority Group across Methods
df_p %>% group_by(AcuteLv, Method) %>% filter(Time_A != "TBD") %>% 
  summarise(mean_SF = round(mean(SF_Score),2)) %>% 
  ggplot(aes(x=Method, y=mean_SF, fill=Method)) + 
   facet_wrap(vars(factor(AcuteLv)), 
               labeller = as_labeller(c(`1` = "Group 1", `2` = "Group 2", 
                      `3` = "Group 3", `4` = "Group 4", `5`="Group 5"))) +
   geom_bar(stat="identity", position=position_dodge()) +
    # scale_fill_manual(values=c(C1= "#004c6d" ,C2="#4998b6", FIFO="#8fecff")) + 
    scale_y_continuous(name = "Mean Satisfaction Score") + 
    scale_x_discrete(name = "Priority Group") +
    scale_fill_brewer(palette="RdBu") + 
    geom_text(size = 1.8, color = 'black', aes(label=mean_SF), 
            position=position_dodge(width=0.9), vjust=-0.2)+
    theme_minimal() + 
    labs(title='Average 15-day Satisfaction Score across Priority Groupse',
            subtitle = "Overcrowding Rate: High",
            caption="Result of 100 simulations") + 
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) 
```






