---
title: "Visualization-2"
author: "Vivian Bui"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
```

```{R}
# Import files each experiment set 
df_er_3a <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3A/Processed/df_er.csv')
df_er_3b <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3B/Processed/df_er.csv')
df_er_3c <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3C/Processed/df_er.csv')

df_p_3a <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3A/Processed/df_p.csv')
df_p_3b <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3B/Processed/df_p.csv')
df_p_3c <- read.csv('~/Desktop/Emergency-Room-Simulation/Patient_Only/Output/3C/Processed/df_p.csv')

# Add column 
df_er_3a <- df_er_3a %>% mutate(Overcrowding = "High")
df_er_3b <- df_er_3b %>% mutate(Overcrowding = "Medium")
df_er_3c <- df_er_3c %>% mutate(Overcrowding = "Low")

df_p_3a <- df_p_3a %>% mutate(Overcrowding = "High") 
df_p_3b <- df_p_3b %>% mutate(Overcrowding = "Medium") 
df_p_3c <- df_p_3c %>% mutate(Overcrowding = "Low") 

# Combine files 
df_er_3 <- rbind(df_er_3a, df_er_3b, df_er_3c)
df_p_3 <- rbind(df_p_3a, df_p_3b, df_p_3c)

# Reorder 
df_er_3 <- df_er_3 %>% mutate(Overcrowding = fct_relevel(Overcrowding, "High", "Medium", "Low"))
df_p_3 <- df_p_3 %>% mutate(Overcrowding = fct_relevel(Overcrowding, "High", "Medium", "Low"))

```

```{r}
# Wait Time by Priority Group 
ggplot(df_p_3, aes(y=Total_Wait_Time, x=Method)) +
    geom_violin() + 
    facet_grid(vars(Overcrowding)) +
    scale_y_continuous(name = "Wait Time") + 
    scale_x_discrete(name = "Method") +
    labs(title = 'Distribution of Wait Time across Methods', 
            caption = "Result of 100 simulations") +  
    theme_bw() +
    theme(plot.title=element_text(hjust=0.5),
          plot.subtitle = element_text(hjust=0.5),
          plot.background=element_blank()) 


```

```{r}

# Compare the % of LWBS in each method 
df_p_3 %>% group_by(Method, Overcrowding) %>% 
  summarise(percent = round(sum(Time_A == "LWBS")*100/n(),2), 
            .groups = 'drop') %>% 
  ggplot(aes(x=Method, y=percent, fill = Overcrowding)) + 
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_y_continuous(name = "Percent of LWBS (%)") + 
  scale_x_discrete(name = "Method") + 
  scale_fill_brewer(palette = "Blues", direction=-1) +
  geom_text(size = 2.5, color = "black", aes(label=percent), 
            position=position_dodge(width=0.9), vjust=-0.8) +
  labs(title = 'The Percentage of LWBS over All Visited Patients',
       subtitle = 'Across Methods and Overcrowding Levels', 
            caption = "Result of 100 simulations",
            fill = "Overcrowding Level") +
  theme_minimal() + 
  theme(plot.title=element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) 

```






